name: TowersPlugin
version: '${project.version}'
main: fr.pikili.towers.towersplugin.TowersPlugin
depend: [WorldGuard]
api-version: '1.20'
commands:
  starttowers:
    description: lancer la partie
  stoptowers:
    description: arreter la partie
  giveitems:
    description: get all custom items
  jointowersblueteam:
    description: join blue team for the towers
  jointowersredteam:
    description: join red team for the towers
  reloadtowers:
    description: recharger la map
  warptowers:
    description: rejoindre la partie de towers pour selection de l'équipe
  leavetowers:
    description: quitter la partiee